architecture:
  description: Core Carbonaut Software Architecture Team
  slack: "#arch"
  members:
  - name: Leonard Pahlke
    github: "leonardpahlke"
  - name: Max Körbächer
    github: "mkorbi"

data:
  description: Core Carbonaut Data Team
  slack: "#data"
  members:
  - name: Christopher Friedrich
    github: "christopherfriedrich"
  - name: Leonard Pahlke
    github: "leonardpahlke"

development:
  description: Core Carbonaut Software Development Team
  slack: "#dev"
  members:
  - name: Leonard Pahlke
    github: "leonardpahlke"
  - name: Christopher Friedrich
    github: "christopherfriedrich"
  - name: Rodrigo Ehlers
    github: "rodrigoehlers"
  - name: Berkay
    github: "bcesur"

governance:
  description: Core Carbonaut Governance Team
  slack: "#general"
  members:
  - name: Leonard Pahlke
    github: "leonardpahlke"
  - name: Max Körbächer
    github: "mkorbi"

maintainers:
  description: Core Carbonaut Maintainers Team
  slack: "#general"
  members:
  - name: Leonard Pahlke
    github: "leonardpahlke"
  - name: Max Körbächer
    github: "mkorbi"
